### ISSUE TITLE
Bug UI/UX - left search bar disappear on scrolling the right content side

### ISSUE THREAD

**Issue by BowTiedDeployer** [hirosystems/docs#132]
### The bug is happening in the following scenarios:
1. access https://docs.hiro.so/api, search anything, for example `nft holdings`  and press it.
2. access the direct link to a given search provides, in this case https://docs.hiro.so/api#tag/Non-Fungible-Tokens/operation/get_nft_holdings 
3. simply scrolling from the top of https://docs.hiro.so/api
### In all cases the search bar reappears after scrolling to the top of the right content side 

![image](https://user-images.githubusercontent.com/93231870/184008526-834a320c-0b84-42ce-9189-45431848cfb0.png)

**Comment by sabbyanandan** [comment]
Thanks for reporting, @BowTiedDeployer.

I initially thought it could be a problem with the redoc itself, but trying out a similar search in their [demo site](https://redocly.github.io/redoc/#tag/store/paths/~1store~1subscribe/post), at least I couldn't reproduce. 

Next, diving into the [`redocusaurus`](https://github.com/rohit-gohri/redocusaurus) plugin we use to generate the static API docs site from the `openapi.yaml`. The dependency versions we use in Docs are old, so this issue is possibly addressed at the latest releases. 

We will look into it carefully. For now, as a workaround, if you click the top-level "Stacks API" tab on the top, you will go back to the previously searched state and the search results view.

**Comment by sabbyanandan** [comment]
There's another OpenAPI plugin, so we could explore different options: https://docusaurus.io/community/resources#search.

**Comment by LakshmiLavanyaKasturi** [comment]
This is fixed.
