### ISSUE TITLE
docs: update docs with Stacks 2.1 information for Hiro products

### ISSUE THREAD

**Issue by elenananana** [hirosystems/docs#137]
Ahead of Stacks 2.1 launch, we need updated docs to reflect any changes the next protocol upgrade will have on Hiro products.

**Comment by sabbyanandan** [comment]
Capturing chatter from slack, so when we get to this, we can document the expectations wrt Clarity1 vs. Clarity2.

**question**
> is the parser v2 backward compatible with Clarity1?
(i think the answer is no, but checking)

It is compatible with Clarity1, but not exactly Epoch 2.05 Clarity1. It's just some minor differences that are incompatible. It'll still be better than specifying Clarity2 because the type checks and what not will be correct. 

> to clarify my question:
> if i write a contract with the parser v2, and don't use clarity2 functions, is my contract compatible with clarity1?

Yes* mostly

> if i load an existing Clarity1 contract, is the parser v2 able to build an AST out of it?

Yes

There are differences between Epoch 2.05 Clarity1 and Epoch 2.1 Clarity1, but they are small. Mostly fixing bugs in the parser v1 behavior that didn't match the expected Clarity1 behavior.
So it would be good if other commands besides the LSP still used parser v1 (by specifying Epoch2.05 so that those minor differences would get caught, for example, before deploying.

**Comment by LakshmiLavanyaKasturi** [comment]
For more info refer to this blog: https://www.youtube.com/watch?v=zZzpGjBcRH0

**Comment by LakshmiLavanyaKasturi** [comment]
Possible changes in the Docs

- Open API Spec
- Stacks 2.0 -> Stacks 2.1

**Comment by sabbyanandan** [comment]
Given the overlapping window in which there can be a stacking bleeding situation, we will have to clearly articulate the Stacks blockchain behavior in this window, and how our products are going to handle the overlapping period with "error messages" or otherwise—all these needs to be captured in 2.1-focused Docs.

**Comment by LakshmiLavanyaKasturi** [comment]
All the possible approaches are noted in the Notion page: https://www.notion.so/hiropbc/Docusaurus-plugins-to-get-remote-content-to-docs-repo-d2a888dbc9a34bc695bb08bf21218c12

Developers can weigh in and suggest what is the approach that they want to go with.

**Comment by elenananana** [comment]
more information here
https://www.hiro.so/blog/a-developers-guide-to-stacks-2-1

**Comment by elenananana** [comment]
> For more info refer to this blog: https://www.youtube.com/watch?v=zZzpGjBcRH0

@LakshmiLavanyaKasturi - I think this is my playlist! 😆 

I shared the blog post above

**Comment by LakshmiLavanyaKasturi** [comment]
Stacks 2.1 migration docs are added for API and StacksJS in the PR: https://github.com/hirosystems/docs/pull/220

**Comment by LakshmiLavanyaKasturi** [comment]
Stacks 2.1 updates are done for API and Stacks JS in - PR: https://github.com/hirosystems/docs/pull/220. 

Clarinet updates are pending.

**Comment by LakshmiLavanyaKasturi** [comment]
All the updates are done. PR #220 is ready for review.

**Comment by LakshmiLavanyaKasturi** [comment]
This is complete.
