### ISSUE TITLE
[Discussion] Switching back to .md files in one docs repo

### ISSUE THREAD

**Issue by janniks** [hirosystems/docs#356]
### Discussion 💭

_Curious to see what other people think of the current docs flow (ie downloading .md files from product repos on deploy)._

The approach is creative and aims to address important issues. I want to check-in on the feeling from the wider-team and answer the problems we intended to solve:
- Has it made our docs more up-to-date?
- Have we seen other improvements due to the flow?

---

I personally feel it has often made working with docs cumbersome and would propose switching back to one unified docs repo (hosting all md files).

_Some instances where I feel the current flow doesn't work well:_
- Deploying needs separate action (in addition to merging the PR on the product repo)
- The product repo doesn't get preview deploys (since it needs the docs repo to have a PR for this); thus we don't know if everything works / renders correctly until we're in production in most cases
- Similarly, local builds don't really work; hacky solutions are needed to test custom components (eg if React code is needed in the main repo for components rendered in a product repo)
- Making changes everywhere (across repos) is hard; each repo needs to be changed and PRs openend (eg changing page titles, links, etc.)
- Unclear product/repo; eg Connect content under Stacks.js, which is a separate repo
- Requires docs-team access to product repos (which might have opinionated rules/flows/commitlints and CI etc.); often requires custom rules/invites or long build times for content-only changes; discourages updates and new content; potentially annoys maintainers

To get around these we have to jump through some annoying hoops, like:
- timing two PRs to deploy at the same time to not interfere with others (when sidebar structure is changed)
- manually setting up symlinks when trying out cross-repo changes locally

---

Would love to hear others thoughts on the matter. Maybe it's just me, so feel free to edit the above issue description as well.. 🙂

**Comment by janniks** [comment]
It also spams/reloads the remote content from github constantly. I think there's a loop where it thinks content was changed, so it rebuilds something, which in turn fetches new content, making it think content was changed, ...
Not sure if easily fixable.

https://github.com/hirosystems/docs/assets/6362150/ebfdb19e-0056-4e45-8a61-6bd9331b71c7

**Comment by diwakergupta** [comment]
Just chiming in here to say that it's very frustrating (and difficult) to debug issues arising from remote-content. Specifically:

* a commit in _any_ of the repos that docs pulls content from can break the docs build: e.g. if you rename a file that's referenced in sidebars.js. There is no good way to catch such build failures, and as the number of repos you pull content from goes up, the likelihood of these kind of failures also goes up.
* such failures, when they happen, are difficult to debug: docusaurus build fails with an unhelpful message and it's non-trivial to figure out exactly which remote-content file is causing the failure. Further, because the failure wasn't introduced by any commit in the docs repo, standard debugging tools like `git bisect` are unusable.

**Comment by csgui** [comment]
Also pulling from several repositories prevents the correct usage of a local development server that, quickly, can reload changes on the documentation.

And that reload loop of remote content from GitHub is really anoying.

It seems that an unique source of data would make the documentation task simple and easy to update. My 2 cents. :-)

**Comment by ryanwaits** [comment]
done
