### ISSUE TITLE
Docs: Replace Thumbs up/down with Canny feedback widget 

### ISSUE THREAD

**Issue by LakshmiLavanyaKasturi** [hirosystems/docs#375]
This issue is integrating the Canny feedback widget to docs [similar to the Hiro Platform.](https://hiro-pbc.canny.io/hiro-platform). 
![image](https://github.com/hirosystems/docs/assets/55154433/6a1d758c-cd3d-4bf3-8989-f948c07be9e0)

The current thumbs-up and down implementation is not very effective in terms of understanding what went wrong in a specific document. 

![image](https://github.com/hirosystems/docs/assets/55154433/22a9963d-dfd5-42a4-b13d-a3994f2f998e)

**Comment by dgarcia360** [comment]
Hi! @ LakshmiLavanyaKasturi ! I found this issue while searching for "feedback widget" on GitHub.

I'm building [PushFeedback](https://pushfeedback.com), a feedback widget tailored for docs sites that integrates well with Docusaurus.

![Feedback for docs](https://github.com/o1-labs/docs2/assets/9107969/1efdd2f1-3bba-40b9-a441-6137b0c14448)

> The current thumbs-up and down implementation is not very effective in terms of understanding what went wrong in a specific document.

+1, feedback is most useful when it is actionable. I was thinking PushFeedback combines well with your current feedback mechanism, since the widget can be triggered from any button. For example, when a user selects the "thumbs down" icon.

We have a free plan for open-source project in exchange of keeping the widget branding. If you're interested in exploring integrating PushFeedback, please [sign up for an account](https://app.pushfeedback.com/accounts/signup/) and let me know to remove the limitations for your project. 

Additionally, I'd be more than happy to assist with a pull request to integrate the [Docusaurus extension](https://docs.pushfeedback.com/installation/docusaurus).

Looking forward to hearing from you!
