### ISSUE TITLE
Docs: Docusaurus : Investigate why Ordinals -> How-to-use-API-key expands other API docs.

### ISSUE THREAD

**Issue by LakshmiLavanyaKasturi** [hirosystems/docs#387]
@janniks, can you please help with this CSS/react fix, perhaps? Thanks!

**Comment by janniks** [comment]
It's because this page: https://github.com/hirosystems/docs/blob/main/docs/how-to-use-api-key.md is being used in multiple parts of the sidebar: https://github.com/hirosystems/docs/blob/320a446137f14f56a2a15e6714513a010984b00a/sidebars.js#L254-L266

I'm not sure there's a simple fix.

The page can be created multiple times across repos and duplicate the content. Or have those pages import a reusable component with the content. If all docs were in one codebase, this would be a bit simpler.

**Comment by LakshmiLavanyaKasturi** [comment]
Investigate and find solutions to avoid the expansion of other docs when one of the "How-to-use-API-keys" documents is opened.
