### ISSUE TITLE
Add docs links to the CLI commands to increase docs visibility

### ISSUE THREAD

**Issue by LakshmiLavanyaKasturi** [hirosystems/docs#414]
This issue is to add docs links to the CLI commands to increase docs visibility.

Eg: my-project git:(develop) ✗ clarinet contracts --help
clarinet-contracts 
Subcommands for working with contracts

USAGE:
    clarinet contracts <SUBCOMMAND>

OPTIONS:
    -h, --help    Print help information

SUBCOMMANDS:
    help    Print this message or the help of the given subcommand(s)
    new     Generate files and settings for a new contract

`clarinet contracts --help` command can have links to how-to-add-contract, how-to-debug-contract, how-to-check-contract and how-to-deploy-contracts.

**Comment by Bhardwaj-Himanshu** [comment]
Hi @LakshmiLavanyaKasturi ,  from my understanding of the problem description we need to add particular commands like what does,
(INPUT)
```bash
clarinet contracts --help
```
(OUTPUT)
```bash
clarinet-contracts
Subcommands for working with contracts

USAGE:
clarinet contracts

OPTIONS:
-h, --help Print help information

SUBCOMMANDS:
help Print this message or the help of the given subcommand(s)
new Generate files and settings for a new contract
```

Like a man-man or man-help command, for finding what does a particular command does in terminal for linux.

*My doubt here being, do we need to document this or add this feature into the program, so that people new to the project could have great help, without googling a lot?*
Also, I know this is issue is not open to be assigned to anyone from outside, but if you are working on anything and I could be of any help let me know!
Thanks
