### ISSUE TITLE
Revisit API feature guides to use consistent names for the titles

### ISSUE THREAD

**Issue by LakshmiLavanyaKasturi** [hirosystems/docs#437]

**Comment by diwakergupta** [comment]
I'm happy to take this but need additional context. @sabbyanandan do you remember / have examples of inconsistencies this issue was trying to address?

**Comment by sabbyanandan** [comment]
@diwakergupta: From what I can recall, the architecture diagram for TMS was under the feature guides and not on the overview page, but it appears to have moved and resolved now.

I had heard about the desire to "merge" features and how-to guides, so that could be an outcome, and you could repurpose this issue for that. @ryanwaits can explain more.

Otherwise, you may want to revise the "title" under the overview pages for all APIs. Currently, I see:
+ Ordinals API Overview
+ Stacks Blockchain API Overview 
+ API - Token Metadata Overview

They can be shortened/expanded/revised for consistency, perhaps. I know it is a nit, but I would do it anyway.

**Comment by ryanwaits** [comment]
closing as this is something that the redesign will take care of + the consolidation of the guides section
