### ISSUE TITLE
Stacks.js / Docs REPL implementation in docs

### ISSUE THREAD

**Issue by LakshmiLavanyaKasturi** [hirosystems/docs#442]
@janniks, Can you help me recall this issue? Thanks!

**Comment by mefrem** [comment]
I believe this refers to the internal hackathon project—https://stacksjs-playground.vercel.app/—that embeds an executable REPL alongside Stacks.js code. 

Note: The REPL works simplest with stacks.js scripts that don't require wallet signing, since we can't assume the developer visiting the docs site has the appropriate wallet signed in, etc.
