### ISSUE TITLE
Remove Netlify?

### ISSUE THREAD

**Issue by janniks** [hirosystems/docs#476]
Should we revisit removing Netlify (form the CI / auto-deploy for docs)? Not sure what the latest on this was, but I don't think it's used anywhere any more.
cc @sabbyanandan

**Comment by sabbyanandan** [comment]
@janniks: Some context -> https://github.com/hirosystems/devops/issues/1267#issuecomment-1648468472

Still, we can and should consolidate if we can make Algolia also work alongside with Vercel, and only that.

**Comment by diwakergupta** [comment]
Can someone explain the dependency between Algolia and Netlify? I don't get it

**Comment by sabbyanandan** [comment]
@diwakergupta: I don't. You can dig-in, perhaps.

**Comment by diwakergupta** [comment]
> @janniks: Some context -> [hirosystems/devops#1267 (comment)](https://github.com/hirosystems/devops/issues/1267#issuecomment-1648468472)
> 
> Still, we can and should consolidate if we can make Algolia also work alongside with Vercel, and only that.

@CharlieC3 do you remember the context here? 

I'm going to remove the integration and see what happens.

**Comment by janniks** [comment]
Yeah, I think we didn't need Netlify to get Algolia to work in the end. But I can't say for certain 😬

**Comment by CharlieC3** [comment]
> do you remember the context here?

Not much more than you may already know. I removed Netlify a couple months back, after which Lavanya found that Algolia requires Netlify for some reason and then she owned that effort ever since. She added Algolia configuration in [this PR](https://github.com/hirosystems/docs/pull/427/files), but I'm not sure if that severed the tie between it and Netlify.

**Comment by ryanwaits** [comment]
closing as this is no longer an issue
