### ISSUE TITLE
Make "How To" Guide Title Convention Consistent

### ISSUE THREAD

**Issue by alexlmiller** [hirosystems/docs#481]
Currently some of the page titles for How To Guides are “How to XXXXXXX” while others are just “XXXXXXX” and the ‘how to’ is implied from the section.

We should pick one format for titles & urls there and rationalize them.

**Comment by alexlmiller** [comment]
CC @ryanwaits on this since it should be a consistent decision across everything

**Comment by ryanwaits** [comment]
since there is no "how to" section anymore i think we can probably close this for now. we do however still mix up the titles of our guides to sometimes say "how to x", which I think is fine with and doesnt need to be standardized everywhere

for example: https://docs.hiro.so/guides/sync-a-bitcoin-node read "how to sync a bitcoin node"

and: https://docs.hiro.so/stacks/stacks.js/guides/broadcast-transactions is just "broadcast transactions"

lmk if this is good to close @alexlmiller
