### ISSUE TITLE
Contributor guide misplaced under .github 

### ISSUE THREAD

**Issue by saralab** [hirosystems/docs#504]
I remember we had a solid contributing.md under the API repo, I see a half baked version under [.github now](https://github.com/hirosystems/stacks-blockchain-api/blob/develop/.github/CONTRIBUTING.md) ( is this intentional?),  can we bring back the version and place it under the root of the repo directly? 
This pattern also seems inconsistent across repositories, let's do a clean sweep and fix this across repos please.

**Comment by mefrem** [comment]
I would guess you mean this guide:
- https://github.com/hirosystems/docs/blob/main/docs/contributors-guide.md
- https://docs.hiro.so/contributors-guide

External dev made some changes to it that are waiting in this PR https://github.com/hirosystems/docs/pull/462

Otherwise, ready to go!

**Comment by csgui** [comment]
@mefrem I think that this issue is more related to the API Contributing Guide.

I've opened a [PR](https://github.com/hirosystems/stacks-blockchain-api/pull/1737) to remove the CONTRIBUTING.md file under the `.github` folder. And also added some changes to the `Contributing Guide` section of the REAME.md file.

And since we have several projects leaving on different repositories, wouldn't be interesting to have a central "Contributing Guide" where all of our projects would link to?
