### ISSUE TITLE
Standardize product screenshots

### ISSUE THREAD

**Issue by ginny-d** [hirosystems/docs#538]
It would be nice to have a standardised screenshot template for product images, for example in here: https://docs.hiro.so/platform/create-project all image formats are different.

**Comment by eugeniadigon** [comment]
> +1. Did you mean the image sizes, or format (webp vs. png etc) or how the screenshots are composed or some combination of these and other factors?

A bit of everything, but mainly how the screenshots are composed (background, aspect ratio/layout, sizes)

**Comment by eugeniadigon** [comment]
@ryanwaits Here are all the edited screenshots for the Platform docs: https://drive.google.com/drive/folders/1xPoRs8P9oZ2_yFLIe0EKpdJlmf_hXWW7?usp=sharing

I don't think I missed screenshots from other products on Docs, but let me know if you find something else that needs/has a screenshot.

A couple of comments:
- On https://docs.hiro.so/stacks/platform/guides/devnet#active-session-management I suggest removing the language around the 30 minutes because there's no timer anymore
- On https://docs.hiro.so/stacks/platform/guides/deployment-plans I suggest replacing the _"It's possible that the transaction may fail in the deployment process..."_ paragraph for a callout (Note), and removing the image below that paragraph because it's outdated

---------------

Here's a preview of how the screenshots look like:

<img width="1186" alt="Frame 316125214" src="https://github.com/user-attachments/assets/82bbd794-f2b7-4a02-a26a-a5b8aac244c8">
