### ISSUE TITLE
Switch from Segment to Google Tag Manager

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/docs#97]
As discussed in https://github.com/hirosystems/docs/issues/90, we want to cleanly switch to Google Tag Manager and rely on it going forward and not rely on Segment's backdoor integration with Google Measurement Protocol API.

**Comment by tprebz** [comment]
Here is the code for the Docs Google Tag Manager container:

To be placed in the &lt;head&gt; of all pages:

```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-59XXGSG');</script>
<!-- End Google Tag Manager -->
```

To be placed immediately after the &lt;body&gt; of all pages, if possible:

```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-59XXGSG"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

**Comment by tprebz** [comment]
The latter (docusaurus-gtm-plugin) is for Google Tag Manager. The gtag plugin is for implementing just Google Analytics.

Since opening this issue, we have also brought on Iterable as our marketing automation platform, and it utilizes Segment integration. So, Segment should remain on Docs for the purposes of the new system, but we would still like to add Google Tag Manager to deliver GA4's tracking tag and to record events/conversions.

**Comment by janniks** [comment]
PR is done; is it okay to merge and receive traffic on GA4 in production (i.e. on docs.hiro.so)?

**Comment by sabbyanandan** [comment]
@janniks: Many thanks! Per my previous discussion with @tprebz, GA4 is already set up and ready for consumption, so I would say go ahead with the merge.

**Comment by tprebz** [comment]
We're ready on the marketing side.

**Comment by janniks** [comment]
Deployed ✅ Using the ID `GTM-59XXGSG` as noted above.

I can't see any traffic coming in yet in GA (maybe it takes a while); In the Admin panel there's no options to send test traffic...

**Comment by tprebz** [comment]
The container in GTM wasn't published. That's now fixed. Data will come into the Hiro Multisite - GA4 property (stream ID 3458954391, measurement ID G-NB2VBT0KY2).

**Comment by janniks** [comment]
Interesting! Can we still filter to only docs.hiro.so events?

**Comment by tprebz** [comment]
Yes, just set hostname as a filter and specify docs.hiro.so. Combining all the sites into a single multisite property lets us see users moving between sites.

We're keeping GA3 in place until that's shut down (just under a year from now), so that can continue to be used if you have existing reports there, but we wanted to begin data collection in GA4 well in advance of the cutoff.

**Comment by janniks** [comment]
_Sort of related:_

We need custom events for https://github.com/hirosystems/docs/pull/107 tracking custom form values and button click (as one event).

Should this be done via Tag Manager (I don't have access), we would need to set up a trigger for the event.
Or should this use Segment ([`track`](https://segment.com/docs/connections/spec/track/) seems to work, but I can't verify — also no Segment access)

**Comment by tprebz** [comment]
@janniks I've added you to the Docs container in Tag Manager with editor permissions so you can experiment with setup there if you like. I have access to marketing's Segment account and can assist there, as well.

**Comment by LakshmiLavanyaKasturi** [comment]
@janniks: Is there anything pending from the docs side to push this PR?

**Comment by janniks** [comment]
PR is live, forgot to re-close this issue.
